---
- name: Create k8s-docker-kubelet drop-in path
  file: path=/etc/systemd/system/k8s-docker-kubelet.service.d state=directory

- name: Create k8s-docker-kubelet path dropin
  template: src=10-override-path.conf.jinja2
            dest=/etc/systemd/system/k8s-docker-kubelet.service.d/10-override-path.conf
  become: yes

- name: Create k8s-docker-kubelet
  template: src=k8s-docker-kubelet.service.jinja2
            dest=/etc/systemd/system/k8s-docker-kubelet.service
  become: yes
  notify:
    - reload systemd
    - restart k8s-docker-kubelet

- name: Ensure k8s-docker-kubelet.service started
  service: name=k8s-docker-kubelet state=started enabled=yes args=--no-block
  become: yes